version: "2"
run:
  modules-download-mode: readonly
  issues-exit-code: 1
  tests: false
linters:
  default: none
  enable:
    - bodyclose
    - dogsled
    - errcheck
    - goconst
    - gocritic
    - gocyclo
    - goheader
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    errcheck:
      exclude-functions:
        - io.Reader.Read
        - io.Writer.Write
    gocognit:
      min-complexity: 20
    gocyclo:
      min-complexity: 15
    revive:
      rules:
        - name: unused-parameter
        - name: unused-return
    staticcheck:
      checks:
        - all
        - -SA1000
        - -SA1019
        - -SA5001
        - -SA5002
        - -ST1000
        - -ST1005
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/myuser/myproject
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
