version: 2

run:
  timeout: 5m

linters:
  enable:
    # 默认启用的linters
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

    # 额外启用的linters
    - gocyclo
    - gochecknoglobals
    - misspell
    - unparam
    - unconvert
    - goconst
    - prealloc
    - predeclared
    - revive
    - nilerr
    - nolintlint
    - godot
    - gocritic

linters-settings:
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US
  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false
        arguments:
          - "checkPrivateReceivers"
          - "sayRepetitiveInsteadOfStutters"

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - gosec
        - gochecknoglobals
    - linters:
        - staticcheck
      text: "SA9003:"
